// The starting Game Index: 100 board games that turn up second hand in NZ, with the facts printed on their boxes
// (year, designer, original publisher, players, playing time, minimum age) and card stats out of 10.
// Facts are from the games' own boxes and rules, not from BoardGameGeek (whose data needs a commercial licence).
// Card stats are Second Turn's own ratings: Strategy (how much skill), Luck (how much dice and draws decide it),
// Social (how much talking, bluffing and laughing), Speed (higher = quicker to play).
// The site loads these into the database the first time it runs; after that, edit them in Admin > Cards.

export type GameKind =
  | "Classic" | "Family" | "Strategy" | "Party" | "Word" | "Trivia" | "Kids" | "Deduction"
  | "Abstract" | "Dexterity" | "Card" | "Dice" | "Co-op" | "Adventure" | "Puzzle";

export type SeedGame = {
  name: string; year: string; designer: string; publisher: string;
  min: number; max: number; minutes: number; age: number; kind: GameKind; mechanics: string;
  strategy: number; luck: number; social: number; speed: number; blurb: string;
};

type Row = [string, string, string, string, number, number, number, number, GameKind, string, number, number, number, number, string];

const rows: Row[] = [
  ["Monopoly", "1935", "Lizzie Magie, Charles Darrow", "Parker Brothers", 2, 8, 120, 8, "Classic", "Roll and move, trading, auction", 4, 7, 7, 2, "Buy, build and bankrupt your family."],
  ["Cluedo", "1949", "Anthony E. Pratt", "Waddingtons", 3, 6, 45, 8, "Deduction", "Deduction, roll and move", 6, 4, 5, 6, "Who, with what, and in which room."],
  ["Scrabble", "1948", "Alfred Mosher Butts", "J.W. Spear & Sons", 2, 4, 90, 8, "Word", "Tile placement, hand management", 8, 3, 3, 4, "100 tiles, 225 squares, endless arguments."],
  ["Trivial Pursuit", "1981", "Chris Haney, Scott Abbott", "Horn Abbot", 2, 6, 90, 12, "Trivia", "Trivia, roll and move", 3, 3, 8, 3, "Fill your pie, one wedge at a time."],
  ["Pictionary", "1985", "Robert Angel", "Angel Games", 3, 16, 60, 12, "Party", "Drawing, teams, timer", 3, 3, 9, 6, "Draw it before the sand runs out."],
  ["Guess Who?", "1979", "Ora Coster, Theo Coster", "Milton Bradley", 2, 2, 20, 6, "Deduction", "Deduction, questions", 4, 2, 4, 8, "Does your person wear glasses?"],
  ["Connect 4", "1974", "Howard Wexler, Ned Strongin", "Milton Bradley", 2, 2, 10, 6, "Abstract", "Pattern building", 6, 1, 3, 9, "Four in a row, and that satisfying clatter."],
  ["Battleship", "1967", "Traditional", "Milton Bradley", 2, 2, 30, 8, "Deduction", "Hidden placement, grid guessing", 4, 4, 3, 6, "B4. Hit. You sank my battleship."],
  ["Mastermind", "1970", "Mordecai Meirowitz", "Invicta Plastics", 2, 2, 20, 8, "Deduction", "Code breaking", 8, 1, 2, 7, "Crack the code in ten guesses."],
  ["Othello", "1973", "Goro Hasegawa", "Tsukuda Original", 2, 2, 30, 8, "Abstract", "Flipping, territory", 8, 1, 2, 7, "A minute to learn, a lifetime to master."],
  ["Chess", "Traditional", "Traditional", "Various", 2, 2, 60, 6, "Abstract", "Movement, capture", 10, 1, 2, 3, "The oldest rivalry on the shelf."],
  ["Draughts", "Traditional", "Traditional", "Various", 2, 2, 30, 6, "Abstract", "Jumping, capture", 7, 1, 2, 6, "Jump, crown, repeat."],
  ["Backgammon", "Traditional", "Traditional", "Various", 2, 2, 30, 8, "Classic", "Dice, racing, betting cube", 6, 6, 3, 6, "Five thousand years of dice and nerve."],
  ["Ludo", "1896", "Traditional (from Pachisi)", "Various", 2, 4, 30, 5, "Kids", "Roll and move, racing", 2, 8, 4, 6, "Race home, and send them back to start."],
  ["Snakes and Ladders", "Traditional", "Traditional (from Moksha Patam)", "Various", 2, 4, 20, 4, "Kids", "Roll and move", 1, 10, 3, 7, "Up the ladders, down the snakes."],
  ["Mouse Trap", "1963", "Marvin Glass and Associates", "Ideal", 2, 4, 30, 6, "Kids", "Building, roll and move", 2, 7, 4, 6, "Build the contraption, catch the mice."],
  ["Operation", "1965", "John Spinello", "Milton Bradley", 1, 6, 15, 6, "Dexterity", "Steady hands, buzzer", 2, 2, 5, 8, "Don't touch the sides."],
  ["Hungry Hippos", "1978", "Fred Kroll", "Milton Bradley", 2, 4, 10, 4, "Kids", "Speed, dexterity", 1, 4, 6, 10, "Loud, fast and marble-hungry."],
  ["Kerplunk", "1967", "Unknown", "Ideal", 2, 4, 20, 5, "Dexterity", "Push your luck, dexterity", 3, 4, 5, 8, "Pull a straw, pray the marbles hold."],
  ["Buckaroo!", "1970", "Unknown", "Milton Bradley", 2, 4, 15, 4, "Dexterity", "Dexterity, push your luck", 1, 6, 5, 9, "Load the mule until it kicks."],
  ["Twister", "1966", "Charles F. Foley, Neil Rabens", "Milton Bradley", 2, 4, 15, 6, "Party", "Spinner, physical", 1, 6, 9, 8, "Left hand, red. Good luck."],
  ["The Game of Life", "1960", "Reuben Klamer, Bill Markham", "Milton Bradley", 2, 6, 60, 8, "Family", "Spinner, roll and move", 2, 8, 5, 4, "Career, kids and a car full of pegs."],
  ["Sorry!", "1934", "William Henry Storey", "Parker Brothers", 2, 4, 30, 6, "Family", "Card-driven movement", 3, 7, 5, 6, "The politest revenge in board games."],
  ["Frustration", "1965", "Unknown", "Kohner Bros", 2, 4, 20, 5, "Kids", "Pop-o-matic dice, racing", 2, 8, 4, 7, "Pop the bubble, race your pegs home."],
  ["Yahtzee", "1956", "Edwin S. Lowe", "E.S. Lowe Company", 1, 10, 30, 8, "Dice", "Dice rolling, set collection", 4, 8, 4, 7, "Five dice, three rolls, one big score."],
  ["Uno", "1971", "Merle Robbins", "International Games", 2, 10, 30, 7, "Card", "Hand management, take that", 3, 7, 7, 8, "Don't forget to call it."],
  ["Rummikub", "1940s", "Ephraim Hertzano", "Lemada", 2, 4, 60, 8, "Classic", "Tile sets, runs", 7, 4, 4, 5, "Rummy with tiles and a lot more thinking."],
  ["Boggle", "1972", "Allan Turoff", "Parker Brothers", 1, 8, 15, 8, "Word", "Word finding, timer", 6, 4, 3, 9, "Shake, flip, find words fast."],
  ["Risk", "1959", "Albert Lamorisse", "Parker Brothers", 2, 6, 120, 10, "Strategy", "Area control, dice battles", 6, 6, 6, 2, "World domination, one dice roll at a time."],
  ["Stratego", "1946", "Jacques Johan Mogendorff", "Jumbo", 2, 2, 45, 8, "Strategy", "Hidden ranks, bluffing", 7, 2, 3, 5, "Find the flag, fear the bomb."],
  ["Escape from Colditz", "1973", "Pat Reid, Brian Degas", "Gibsons Games", 2, 6, 120, 12, "Strategy", "Asymmetric, roll and move", 6, 5, 6, 3, "Prisoners against guards, from a real escaper."],
  ["Downfall", "1970", "Unknown", "Milton Bradley", 2, 2, 20, 7, "Abstract", "Dial turning, planning", 6, 1, 2, 7, "Turn the dials, drop your discs first."],
  ["Hotels", "1986", "Unknown", "Milton Bradley", 2, 4, 90, 8, "Family", "Building, roll and move", 4, 7, 6, 3, "3D hotels and ruthless rents."],
  ["Balderdash", "1984", "Laura Robinson, Paul Toyne", "Canada Games", 2, 6, 60, 12, "Party", "Bluffing, voting", 3, 3, 9, 5, "Make up a definition, fool your friends."],
  ["Scattergories", "1988", "Unknown", "Milton Bradley", 2, 6, 30, 12, "Word", "Categories, timer", 4, 3, 8, 7, "One letter, twelve categories, one minute."],
  ["Taboo", "1989", "Brian Hersch", "Milton Bradley", 4, 10, 30, 12, "Party", "Word guessing, teams", 3, 2, 9, 8, "Describe it without the forbidden words."],
  ["Articulate!", "1992", "Unknown", "Drumond Park", 4, 20, 60, 12, "Party", "Describing, teams", 2, 3, 9, 7, "The fast-talking describing game."],
  ["Cranium", "1998", "Richard Tait, Whit Alexander", "Cranium Inc.", 4, 16, 60, 12, "Party", "Mixed challenges, teams", 3, 3, 9, 5, "Draw, sculpt, act and answer."],
  ["HeroQuest", "1989", "Stephen Baker", "Milton Bradley", 2, 5, 90, 10, "Adventure", "Dungeon crawl, dice combat", 5, 6, 6, 3, "Heroes against the evil sorcerer, Morcar."],
  ["Space Crusade", "1990", "Stephen Baker", "Milton Bradley", 2, 4, 90, 10, "Adventure", "Tactical, dice combat", 5, 6, 5, 3, "Space marines aboard an alien hulk."],
  ["Atmosfear", "1991", "Phillip Tanner, Brett Clements", "A Couple 'A Cowboys", 3, 6, 60, 12, "Party", "VHS timer, racing", 2, 6, 8, 6, "The Gatekeeper is watching. Australian-made."],
  ["Jumanji", "1995", "Unknown", "Milton Bradley", 2, 4, 30, 8, "Family", "Roll and move, co-op race", 2, 8, 5, 6, "The film's game, without the stampede."],
  ["Crocodile Dentist", "1990", "Unknown", "Milton Bradley", 1, 4, 10, 4, "Kids", "Push your luck", 1, 9, 6, 10, "Press a tooth. Hope it doesn't bite."],
  ["Catan", "1995", "Klaus Teuber", "Kosmos", 3, 4, 90, 10, "Strategy", "Trading, dice production, building", 7, 5, 8, 4, "Trade wood for sheep and build an island."],
  ["Carcassonne", "2000", "Klaus-Jürgen Wrede", "Hans im Glück", 2, 5, 40, 7, "Strategy", "Tile placement, area control", 6, 4, 4, 6, "Build a medieval landscape, tile by tile."],
  ["Ticket to Ride", "2004", "Alan R. Moon", "Days of Wonder", 2, 5, 60, 8, "Family", "Set collection, route building", 6, 4, 5, 5, "Claim train routes across America."],
  ["Pandemic", "2008", "Matt Leacock", "Z-Man Games", 2, 4, 45, 8, "Co-op", "Co-operative, hand management", 8, 4, 7, 5, "Work together to stop four diseases."],
  ["Dixit", "2008", "Jean-Louis Roubira", "Libellud", 3, 6, 30, 8, "Party", "Storytelling, voting", 4, 2, 9, 7, "Dreamlike cards and clever clues."],
  ["Sushi Go!", "2013", "Phil Walker-Harding", "Gamewright", 2, 5, 15, 8, "Card", "Card drafting, set collection", 5, 4, 4, 9, "Pass the plates, grab the best sushi."],
  ["Codenames", "2015", "Vlaada Chvátil", "Czech Games Edition", 2, 8, 15, 14, "Party", "Word clues, teams", 6, 1, 9, 8, "One-word clues, two rival spymasters."],
  ["Exploding Kittens", "2015", "Elan Lee, Matthew Inman, Shane Small", "Exploding Kittens", 2, 5, 15, 7, "Card", "Push your luck, take that", 3, 7, 7, 9, "Russian roulette, with cats."],
  ["Dobble", "2009", "Denis Blanchot", "Play Factory", 2, 8, 15, 6, "Party", "Pattern spotting, speed", 2, 3, 6, 10, "There's always exactly one match."],
  ["Jenga", "1983", "Leslie Scott", "Leslie Scott (later Hasbro)", 1, 8, 20, 6, "Dexterity", "Stacking, steady hands", 3, 3, 7, 9, "54 blocks and a lot of held breath."],
  ["Rush Hour", "1996", "Nob Yoshigahara", "Binary Arts (ThinkFun)", 1, 1, 20, 8, "Puzzle", "Sliding block puzzle", 8, 1, 1, 7, "Slide the cars, free the red one."],
  ["Labyrinth", "1986", "Max J. Kobbert", "Ravensburger", 2, 4, 30, 7, "Family", "Tile sliding, maze", 5, 4, 4, 6, "Shift the maze to reach your treasure."],
  ["Mancala", "Traditional", "Traditional", "Various", 2, 2, 15, 6, "Abstract", "Sowing, capture", 7, 1, 3, 8, "Sow the seeds, capture the most."],
  ["Dominoes", "Traditional", "Traditional", "Various", 2, 4, 30, 6, "Classic", "Matching, tile laying", 5, 5, 4, 7, "Match the spots, block the rest."],
  ["Cribbage", "Traditional", "John Suckling (traditionally credited)", "Various", 2, 4, 30, 10, "Card", "Card play, pegging", 7, 5, 4, 6, "Fifteen two, fifteen four, and a pair is six."],
  ["Pass the Pigs", "1977", "David Moffat", "Milton Bradley", 2, 6, 15, 7, "Dice", "Push your luck", 1, 9, 6, 9, "Roll pigs, score points, don't get greedy."],
  ["Kingdomino", "2016", "Bruno Cathala", "Blue Orange", 2, 4, 15, 8, "Family", "Tile drafting, grid building", 6, 4, 3, 8, "Build a 5×5 kingdom of dominoes."],
  ["Splendor", "2014", "Marc André", "Space Cowboys", 2, 4, 30, 10, "Strategy", "Engine building, set collection", 7, 3, 3, 6, "Gems, mines and visiting nobles."],
  ["Azul", "2017", "Michael Kiesling", "Next Move Games", 2, 4, 40, 8, "Abstract", "Pattern building, drafting", 7, 2, 3, 6, "Lay beautiful tiles, avoid the floor."],
  ["7 Wonders", "2010", "Antoine Bauza", "Repos Production", 3, 7, 30, 10, "Strategy", "Card drafting, civilisation", 7, 3, 4, 6, "Build a wonder of the ancient world."],
  ["Love Letter", "2012", "Seiji Kanai", "Alderac Entertainment Group", 2, 4, 20, 10, "Card", "Deduction, player elimination", 5, 6, 6, 9, "Sixteen cards of courtly intrigue."],
  ["King of Tokyo", "2011", "Richard Garfield", "IELLO", 2, 6, 30, 8, "Family", "Dice, king of the hill", 4, 8, 7, 7, "Giant monsters fight over Tokyo."],
  ["Forbidden Island", "2010", "Matt Leacock", "Gamewright", 2, 4, 30, 10, "Co-op", "Co-operative, set collection", 6, 4, 7, 6, "Grab the treasures before the island sinks."],
  ["Qwirkle", "2006", "Susan McKinley Ross", "MindWare", 2, 4, 45, 6, "Abstract", "Tile matching, pattern building", 6, 4, 3, 6, "Match colours and shapes for big scores."],
  ["Blokus", "2000", "Bernard Tavitian", "Sekkoïa", 2, 4, 20, 7, "Abstract", "Territory, spatial", 7, 1, 3, 7, "Corner to corner, block your rivals."],
  ["Bananagrams", "2006", "Abe Nathanson, Rena Nathanson", "Bananagrams", 1, 8, 15, 7, "Word", "Speed word building", 6, 3, 4, 9, "Scrabble at speed, in a banana."],
  ["Apples to Apples", "1999", "Matthew Kirby, Mark Osterhaus", "Out of the Box Publishing", 4, 10, 30, 12, "Party", "Judging, card matching", 2, 4, 9, 7, "Match the funniest card to the word."],
  ["Monopoly Deal", "2008", "Katharine Chapman", "Hasbro", 2, 5, 15, 8, "Card", "Set collection, take that", 5, 5, 6, 8, "Monopoly in fifteen minutes."],
  ["Perfection", "1973", "Unknown", "Lakeside", 1, 4, 5, 5, "Dexterity", "Speed, shape matching", 2, 2, 3, 10, "Fit every shape before it pops."],
  ["Simon", "1978", "Ralph Baer, Howard J. Morrison", "Milton Bradley", 1, 4, 10, 7, "Classic", "Memory, electronic", 4, 1, 3, 9, "Remember the lights, repeat the tune."],
  ["Pop-Up Pirate", "1975", "Unknown", "Tomy", 2, 4, 5, 4, "Kids", "Push your luck", 1, 10, 6, 10, "One sword sends the pirate flying."],
  ["Don't Break the Ice", "1968", "Unknown", "Schaper", 2, 4, 10, 3, "Kids", "Dexterity, push your luck", 2, 5, 5, 9, "Tap out the ice, keep the skater up."],
  ["Carrom", "Traditional", "Traditional", "Various", 2, 4, 30, 8, "Dexterity", "Flicking, aiming", 6, 3, 4, 6, "Flick the striker, pocket the pieces."],
  ["Chinese Checkers", "1892", "Traditional (Stern-Halma)", "Various", 2, 6, 30, 6, "Abstract", "Hopping, racing", 6, 1, 4, 6, "Hop across the star to the far corner."],
  ["Nine Men's Morris", "Traditional", "Traditional", "Various", 2, 2, 15, 7, "Abstract", "Placement, capture", 7, 1, 2, 8, "Make a mill, take a man."],
  ["Go", "Traditional", "Traditional", "Various", 2, 2, 60, 8, "Abstract", "Territory, capture", 10, 1, 2, 2, "Black and white stones, endless depth."],
  ["Mahjong", "Traditional", "Traditional", "Various", 4, 4, 120, 12, "Classic", "Tile sets, hand building", 7, 5, 6, 3, "Tiles, winds and dragons."],
  ["Diplomacy", "1959", "Allan B. Calhamer", "Games Research Inc.", 2, 7, 240, 12, "Strategy", "Negotiation, simultaneous orders", 9, 1, 10, 1, "No dice. Just alliances and betrayal."],
  ["Axis & Allies", "1981", "Larry Harris", "Milton Bradley", 2, 5, 240, 12, "Strategy", "Wargame, dice combat", 8, 6, 5, 1, "The Second World War on your table."],
  ["Acquire", "1964", "Sid Sackson", "3M", 2, 6, 90, 12, "Strategy", "Stocks, tile placement", 8, 4, 5, 4, "Merge hotel chains, cash in your shares."],
  ["Careers", "1955", "James Cooke Brown", "Parker Brothers", 2, 6, 60, 8, "Family", "Roll and move, secret goals", 4, 6, 5, 4, "Fame, fortune and happiness, your mix."],
  ["Squatter", "1962", "Robert Lloyd", "", 2, 6, 120, 10, "Family", "Roll and move, farming", 5, 7, 5, 2, "Run a sheep station, Australian style."],
  ["Scotland Yard", "1983", "Werner Schlegel and others", "Ravensburger", 3, 6, 45, 10, "Deduction", "Hidden movement, co-op hunt", 7, 2, 7, 5, "Track Mister X across London."],
  ["Payday", "1975", "Paul J. Gruen", "Parker Brothers", 2, 4, 60, 8, "Family", "Roll and move, money", 3, 7, 4, 4, "Bills, deals and getting to payday."],
  ["Masterpiece", "1970", "Unknown", "Parker Brothers", 3, 6, 60, 10, "Family", "Auction, bluffing", 4, 6, 7, 4, "Bid on great paintings. Some are forgeries."],
  ["Dungeon!", "1975", "David R. Megarry", "TSR", 1, 8, 60, 8, "Adventure", "Dungeon crawl, dice combat", 3, 8, 5, 5, "Delve deeper for bigger treasure."],
  ["Hare & Tortoise", "1974", "David Parlett", "Intellect Games", 2, 6, 45, 8, "Strategy", "Racing, resource management", 7, 2, 4, 5, "No dice. Carrots, lettuce and clever pacing."],
  ["Sequence", "1982", "Douglas Reuter", "Jax Ltd", 2, 12, 30, 7, "Family", "Cards and board, five in a row", 5, 6, 6, 6, "Play a card, claim a space, make five."],
  ["Mysterium", "2015", "Oleksandr Nevskiy, Oleg Sidorenko", "Libellud", 2, 7, 42, 10, "Co-op", "Co-operative deduction", 5, 3, 8, 5, "A ghost sends visions to solve its murder."],
  ["Hanabi", "2010", "Antoine Bauza", "Les XII Singes", 2, 5, 25, 8, "Co-op", "Co-operative, hidden hands", 7, 3, 8, 7, "Make fireworks without seeing your own cards."],
  ["Timeline", "2010", "Frédéric Henry", "Asmodee", 2, 8, 15, 8, "Trivia", "Ordering, trivia", 4, 4, 5, 9, "Place inventions in the right order."],
  ["The Mind", "2018", "Wolfgang Warsch", "Nürnberger-Spielkarten-Verlag", 2, 4, 20, 8, "Co-op", "Co-operative, silent timing", 4, 4, 8, 9, "Play cards in order, without talking."],
  ["Skull", "2011", "Hervé Marly", "Lui-même", 3, 6, 30, 10, "Party", "Bluffing, bidding", 5, 3, 9, 8, "Roses and one skull. Who's bluffing?"],
  ["Coup", "2012", "Rikki Tahta", "La Mame Games", 2, 6, 15, 13, "Card", "Bluffing, player elimination", 6, 3, 9, 9, "Lie about your roles, outlast the rest."],
  ["Wingspan", "2019", "Elizabeth Hargrave", "Stonemaier Games", 1, 5, 70, 10, "Strategy", "Engine building, card play", 8, 4, 3, 3, "Attract birds to your wildlife reserve."],
  ["Tiddlywinks", "1888", "Joseph Fincher", "Various", 2, 4, 20, 6, "Dexterity", "Flicking", 3, 3, 5, 7, "Squop, squidger and a flick into the pot."],
  ["Fireball Island", "1986", "Bruce Lund, Chuck Kennedy", "Milton Bradley", 2, 4, 30, 7, "Family", "Roll and move, marbles", 2, 7, 6, 6, "Grab the jewel, dodge the fireballs."],
];

export const seedGames: SeedGame[] = rows.map(([name, year, designer, publisher, min, max, minutes, age, kind, mechanics, strategy, luck, social, speed, blurb]) => ({
  name, year, designer, publisher, min, max, minutes, age, kind, mechanics, strategy, luck, social, speed, blurb,
}));
